### ISSUE TITLE
Offer to assist... if I can get it running locally...

### ISSUE THREAD

**Issue by adigitalnative** [skandragon/thing#148]
Hey there,

I'm a Ruby/Rails dev in Atlantia. I figured I'd fork & pull your repo to see if I could get it running locally, with an eye to contributing/offering pull requests for the project down the road.

I'm running into a roadblock in getting the app running locally and wondering if you have any insight. (plus it might be something that gets in the way if you ever need to redeploy on a new server, so may generally be useful...)

I'm running rake db:migrate and hitting an error at migration 20130204210202 MakeRequestedTimesAnArray. Stack trace is below, but it seems to be looking for a 'year' column on 'Instructables' - which doesn't exist.

Thoughts/workarounds?

JQ (SKA Marguerite d'Cheneau)

'''
thing » be rake db:migrate

... handwaving successful migrations...

== 20130204210202 MakeRequestedTimesAnArray: migrating ========================
-- add_column(:instructables, :requested_times, :string, {:array=>true})
   -> 0.0015s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column instructables.year does not exist
LINE 1: ...LECT "instructables".* FROM "instructables" WHERE "instructa...
                                                             ^
: SELECT "instructables".* FROM "instructables" WHERE "instructables"."year" = $1
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rack-mini-profiler-1.0.0/lib/patches/db/pg.rb:47:in `prepare'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rack-mini-profiler-1.0.0/lib/patches/db/pg.rb:47:in `prepare'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `prepare_statement'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:604:in `exec_cache'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:591:in `execute_and_clear'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:706:in `exec_queries'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:583:in `load'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:260:in `records'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation/delegation.rb:38:in `each'
/Users/jq/Development/sca_thing/thing/db/migrate/20130204210202_make_requested_times_an_array.rb:6:in `up'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:792:in `exec_migration'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:772:in `block in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:771:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration/compatibility.rb:121:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:951:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `block in ddl_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/transactions.rb:211:in `transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `each'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `block in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1006:in `up'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:984:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/tasks/database_tasks.rb:163:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/jq/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `eval'
/Users/jq/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column instructables.year does not exist
LINE 1: ...LECT "instructables".* FROM "instructables" WHERE "instructa...
                                                             ^
: SELECT "instructables".* FROM "instructables" WHERE "instructables"."year" = $1
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rack-mini-profiler-1.0.0/lib/patches/db/pg.rb:47:in `prepare'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rack-mini-profiler-1.0.0/lib/patches/db/pg.rb:47:in `prepare'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `prepare_statement'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:604:in `exec_cache'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:591:in `execute_and_clear'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:706:in `exec_queries'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:583:in `load'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:260:in `records'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation/delegation.rb:38:in `each'
/Users/jq/Development/sca_thing/thing/db/migrate/20130204210202_make_requested_times_an_array.rb:6:in `up'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:792:in `exec_migration'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:772:in `block in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:771:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration/compatibility.rb:121:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:951:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `block in ddl_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/transactions.rb:211:in `transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `each'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `block in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1006:in `up'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:984:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/tasks/database_tasks.rb:163:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/jq/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `eval'
/Users/jq/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
PG::UndefinedColumn: ERROR:  column instructables.year does not exist
LINE 1: ...LECT "instructables".* FROM "instructables" WHERE "instructa...
                                                             ^
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rack-mini-profiler-1.0.0/lib/patches/db/pg.rb:47:in `prepare'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rack-mini-profiler-1.0.0/lib/patches/db/pg.rb:47:in `prepare'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `prepare_statement'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:604:in `exec_cache'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql_adapter.rb:591:in `execute_and_clear'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:706:in `exec_queries'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:583:in `load'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation.rb:260:in `records'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/relation/delegation.rb:38:in `each'
/Users/jq/Development/sca_thing/thing/db/migrate/20130204210202_make_requested_times_an_array.rb:6:in `up'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:792:in `exec_migration'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:772:in `block in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:771:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration/compatibility.rb:121:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:951:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `block in ddl_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/transactions.rb:211:in `transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `each'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `block in migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:1006:in `up'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/migration.rb:984:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/tasks/database_tasks.rb:163:in `migrate'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/activerecord-5.0.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/jq/.rvm/gems/ruby-2.4.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/jq/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `eval'
/Users/jq/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
'''

**Comment by Cordelya** [comment]
I just ran into the same error. Here's how I corrected it, for anybody else who is having this problem and finds this issue.

I loaded db/structure.sql into each database manually, then ran migrate and it worked fine - all the way through starting rails and getting the front page to load.
